-- ████████████████████████████████████████████████████████████████████████
-- ██                                                                    ██
-- ██   VORTEX — DDL CONSOLIDADO  v2  (PostgreSQL 16 / Supabase)         ██
-- ██   E-commerce de Ropa Urbana / Streetwear con Asistente IA          ██
-- ██   Schema: vortex   |   2026                                        ██
-- ██                                                                    ██
-- ████████████████████████████████████████████████████████████████████████
--
--  ARQUITECTURA: Inventario por variante (talla × color)
--  ─────────────────────────────────────────────────────
--  La unidad atómica de stock NO es el producto — es la variante.
--  Cada combinación (producto × talla × color) tiene su propio saldo.
--
--  STACK:
--    DB        : Supabase PostgreSQL 16 + pgvector
--    Embeddings: Voyage AI (voyage-3, 1024 dims)
--    Chat IA   : Anthropic Claude (claude-sonnet-4-5)
--    Backend   : Node.js 20 + Express + Prisma 5
--    Imágenes  : Azure Blob Storage (URL pública directa)
--
--  CONVENCIONES DE NOMBRADO:
--    pk_<tabla>          — primary key
--    fk_<orig>_<dest>    — foreign key
--    uq_<col>            — unique constraint
--    chk_<col>           — check constraint
--    idx_<tabla>_<col>   — índice no-único
--    var_*               — columnas de stock en variante_producto
--
--  TOTAL TABLAS  : 25
--  EXTENSIONS    :  2  (vector, pgcrypto)
--  TRIGGERS      :  X  (updated_at automático)
--  GENERATED     :  2  (var_saldo_final, subtotal_linea)
-- ████████████████████████████████████████████████████████████████████████


-- ════════════════════════════════════════════════════════════════════════
--  BLOQUE 0 — SCHEMA, EXTENSIONS, SECUENCIAS, FUNCIONES UTILITARIAS
-- ════════════════════════════════════════════════════════════════════════

DROP SCHEMA IF EXISTS vortex CASCADE;
CREATE SCHEMA vortex;
SET search_path TO vortex, public;

COMMENT ON SCHEMA vortex IS
    'VORTEX — E-commerce de ropa urbana con asistente IA. Inventario por variante.';

-- ── Extensions ──────────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS vector;       -- pgvector — embeddings semánticos
CREATE EXTENSION IF NOT EXISTS pgcrypto;     -- gen_random_uuid() para sesiones de chat

-- ── Secuencias ──────────────────────────────────────────────────────────
CREATE SEQUENCE seq_producto
    START WITH 1
    INCREMENT BY 1
    NO CYCLE;

COMMENT ON SEQUENCE seq_producto IS
    'Genera IDs de producto formato P000001 — usada en producto.id_producto DEFAULT';

-- ── Función trigger genérica para mantener updated_at ───────────────────
CREATE OR REPLACE FUNCTION fn_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION fn_set_updated_at() IS
    'Trigger genérico: setea updated_at en CURRENT_TIMESTAMP en cada UPDATE';


-- ════════════════════════════════════════════════════════════════════════
--  BLOQUE 1 — ACTORES Y SEGURIDAD
-- ════════════════════════════════════════════════════════════════════════

-- --------------------------------------------------------------------
--  1.1  ROL — roles del personal de backoffice
-- --------------------------------------------------------------------
CREATE TABLE rol (
    id_rol      INTEGER     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nombre      VARCHAR(50) NOT NULL,
    descripcion VARCHAR(200),
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_rol           PRIMARY KEY (id_rol),
    CONSTRAINT uq_rol_nombre    UNIQUE      (nombre)
);
COMMENT ON TABLE rol IS
    'Roles del personal de backoffice (admin, vendedor, bodega, marketing, etc.)';


-- --------------------------------------------------------------------
--  1.2  EMPLEADO — personal interno
-- --------------------------------------------------------------------
CREATE TABLE empleado (
    id_empleado     INTEGER     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    cedula          VARCHAR(13) NOT NULL,
    nombre1         VARCHAR(40) NOT NULL,
    apellido1       VARCHAR(40) NOT NULL,
    telefono        VARCHAR(20),
    estado_emp      CHAR(3)     NOT NULL DEFAULT 'ACT',
    created_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_empleado          PRIMARY KEY (id_empleado),
    CONSTRAINT uq_emp_cedula        UNIQUE      (cedula),
    CONSTRAINT chk_emp_cedula       CHECK (LENGTH(TRIM(cedula)) IN (10, 13)),
    CONSTRAINT chk_emp_estado       CHECK (estado_emp IN ('ACT','INA'))
);
COMMENT ON TABLE empleado IS
    'Empleados internos. Acceso al backoffice mediante usuarios_backoffice.';


-- --------------------------------------------------------------------
--  1.3  USUARIOS_BACKOFFICE — credenciales del personal
-- --------------------------------------------------------------------
CREATE TABLE usuarios_backoffice (
    id_usuario      INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email           VARCHAR(100)    NOT NULL,
    password_hash   VARCHAR(255)    NOT NULL,
    id_rol          INTEGER         NOT NULL,
    id_empleado     INTEGER         NOT NULL,
    ultimo_login    TIMESTAMP,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_usuarios_backoffice  PRIMARY KEY (id_usuario),
    CONSTRAINT uq_ubo_email            UNIQUE      (email),
    CONSTRAINT uq_ubo_empleado         UNIQUE      (id_empleado),
    CONSTRAINT fk_ubo_rol              FOREIGN KEY (id_rol)
        REFERENCES rol(id_rol)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_ubo_empleado         FOREIGN KEY (id_empleado)
        REFERENCES empleado(id_empleado)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT chk_ubo_email           CHECK (email LIKE '%@%.%')
);
COMMENT ON TABLE usuarios_backoffice IS
    'Credenciales de empleados para acceder al panel de administración';
COMMENT ON COLUMN usuarios_backoffice.password_hash IS
    'bcrypt o argon2id — NUNCA texto plano. Anchura 255 cubre todos los algoritmos modernos.';


-- --------------------------------------------------------------------
--  1.4  CLIENTE — usuarios de la tienda (login con email)
-- --------------------------------------------------------------------
CREATE TABLE cliente (
    id_cliente      INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email           VARCHAR(100)    NOT NULL,
    password_hash   VARCHAR(255)    NOT NULL,
    ruc_cedula      VARCHAR(13)     NOT NULL,
    telefono        VARCHAR(20),
    nombre1         VARCHAR(40)     NOT NULL,
    apellido1       VARCHAR(40)     NOT NULL,
    email_verificado BOOLEAN        NOT NULL DEFAULT FALSE,
    estado          CHAR(3)         NOT NULL DEFAULT 'ACT',
    ultimo_login    TIMESTAMP,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_cliente           PRIMARY KEY (id_cliente),
    CONSTRAINT uq_cli_email         UNIQUE      (email),
    CONSTRAINT uq_cli_ruc_cedula    UNIQUE      (ruc_cedula),
    CONSTRAINT chk_cli_ruc_cedula   CHECK (LENGTH(TRIM(ruc_cedula)) IN (10, 13)),
    CONSTRAINT chk_cli_email        CHECK (email LIKE '%@%.%'),
    CONSTRAINT chk_cli_estado       CHECK (estado IN ('ACT','INA','BLO'))
);
COMMENT ON TABLE cliente IS
    'Clientes de la tienda. Login con email. Estados: ACT=Activo, INA=Inactivo, BLO=Bloqueado.';
COMMENT ON COLUMN cliente.email_verificado IS
    'TRUE solo cuando el cliente confirmó su email mediante token_recuperacion(EMAIL_VERIFY)';


-- --------------------------------------------------------------------
--  1.5  DIRECCION_CLIENTE — direcciones de envío del cliente (1:N)
-- --------------------------------------------------------------------
CREATE TABLE direccion_cliente (
    id_direccion        INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_cliente          INTEGER         NOT NULL,
    alias               VARCHAR(30)     NOT NULL,
    nombre_destinatario VARCHAR(80)     NOT NULL,
    telefono_contacto   VARCHAR(20)     NOT NULL,
    provincia           VARCHAR(50)     NOT NULL,
    ciudad              VARCHAR(50)     NOT NULL,
    direccion           VARCHAR(200)    NOT NULL,
    referencia          VARCHAR(200),
    codigo_postal       VARCHAR(10),
    es_principal        BOOLEAN         NOT NULL DEFAULT FALSE,
    activa              BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_direccion_cliente PRIMARY KEY (id_direccion),
    CONSTRAINT fk_dir_cliente       FOREIGN KEY (id_cliente)
        REFERENCES cliente(id_cliente)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT chk_dir_alias        CHECK (LENGTH(TRIM(alias)) > 0),
    CONSTRAINT chk_dir_telefono     CHECK (LENGTH(TRIM(telefono_contacto)) >= 7)
);
COMMENT ON TABLE direccion_cliente IS
    'Direcciones de envío del cliente. Permite múltiples (casa, trabajo, etc.).';
COMMENT ON COLUMN direccion_cliente.activa IS
    'Soft-delete: FALSE oculta la dirección al cliente pero preserva referencias en facturas históricas.';

-- Una sola dirección principal por cliente (índice parcial único)
CREATE UNIQUE INDEX uq_direccion_principal
    ON direccion_cliente (id_cliente)
    WHERE es_principal = TRUE;

COMMENT ON INDEX uq_direccion_principal IS
    'Garantiza que cada cliente tenga máximo una dirección marcada como principal';


-- --------------------------------------------------------------------
--  1.6  TOKEN_RECUPERACION — tokens de password reset y email verify
-- --------------------------------------------------------------------
CREATE TABLE token_recuperacion (
    id_token        UUID            NOT NULL DEFAULT gen_random_uuid(),
    id_cliente      INTEGER         NOT NULL,
    tipo            VARCHAR(20)     NOT NULL,
    expira          TIMESTAMP       NOT NULL,
    usado           BOOLEAN         NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_token_recuperacion PRIMARY KEY (id_token),
    CONSTRAINT fk_tok_cliente        FOREIGN KEY (id_cliente)
        REFERENCES cliente(id_cliente)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT chk_tok_tipo          CHECK (tipo IN ('PASSWORD_RESET','EMAIL_VERIFY')),
    CONSTRAINT chk_tok_expira        CHECK (expira > created_at)
);
COMMENT ON TABLE token_recuperacion IS
    'Tokens de un solo uso para reset de password y verificación de email';


-- ════════════════════════════════════════════════════════════════════════
--  BLOQUE 2 — CATÁLOGO DE PRODUCTOS
-- ════════════════════════════════════════════════════════════════════════

-- --------------------------------------------------------------------
--  2.1  CATEGORIA_PRODUCTO
-- --------------------------------------------------------------------
CREATE TABLE categoria_producto (
    id_categoria    CHAR(3)     NOT NULL,
    nombre          VARCHAR(50) NOT NULL,
    descripcion     VARCHAR(200),
    orden           SMALLINT    NOT NULL DEFAULT 0,
    estado          CHAR(3)     NOT NULL DEFAULT 'ACT',
    created_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_categoria_producto PRIMARY KEY (id_categoria),
    CONSTRAINT uq_cat_nombre         UNIQUE      (nombre),
    CONSTRAINT chk_estado_cat        CHECK (estado IN ('ACT','INA'))
);
COMMENT ON TABLE categoria_producto IS
    'Categorías visibles al cliente: HOO=Hoodies, TEE=T-shirts, PAN=Pants, ACC=Accessories, etc.';
COMMENT ON COLUMN categoria_producto.orden IS
    'Orden de aparición en el menú del e-commerce. Independiente del id_categoria.';


-- --------------------------------------------------------------------
--  2.2  TALLA — catálogo maestro
-- --------------------------------------------------------------------
CREATE TABLE talla (
    id_talla        INTEGER     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    descripcion     VARCHAR(10) NOT NULL,
    orden           SMALLINT    NOT NULL DEFAULT 0,
    estado          CHAR(3)     NOT NULL DEFAULT 'ACT',
    created_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_talla         PRIMARY KEY (id_talla),
    CONSTRAINT uq_tal_desc      UNIQUE      (descripcion),
    CONSTRAINT chk_tal_estado   CHECK (estado IN ('ACT','INA'))
);
COMMENT ON TABLE talla IS
    'Tallas del catálogo: XS, S, M, L, XL, Única.';
COMMENT ON COLUMN talla.orden IS
    'Orden de visualización: 1=XS, 2=S, 3=M, 4=L, 5=XL — independiente del id';


-- --------------------------------------------------------------------
--  2.3  PRODUCTO — concepto comercial (sin stock)
-- --------------------------------------------------------------------
CREATE TABLE producto (
    id_producto     VARCHAR(7)      NOT NULL DEFAULT
        ('P' || LPAD(NEXTVAL('seq_producto')::TEXT, 6, '0')),
    id_categoria    CHAR(3)         NOT NULL,
    nombre          VARCHAR(80)     NOT NULL,
    descripcion_corta VARCHAR(200),
    precio_venta    NUMERIC(10,2)   NOT NULL DEFAULT 0.00,
    estado_prod     CHAR(3)         NOT NULL DEFAULT 'ACT',
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_producto          PRIMARY KEY (id_producto),
    CONSTRAINT uq_pro_nombre        UNIQUE      (nombre),
    CONSTRAINT fk_pro_categoria     FOREIGN KEY (id_categoria)
        REFERENCES categoria_producto(id_categoria)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_pro_precio       CHECK (precio_venta >= 0),
    CONSTRAINT chk_estado_prod      CHECK (estado_prod IN ('ACT','INA'))
);
COMMENT ON TABLE producto IS
    'Producto a nivel de catálogo. El stock real está en variante_producto. La descripción rica generada por IA está en producto_ai.';
COMMENT ON COLUMN producto.descripcion_corta IS
    'Descripción breve manual para vistas previas. La descripción larga IA está en producto_ai.';
COMMENT ON COLUMN producto.precio_venta IS
    'Precio base. Promociones se aplican vía promocion_detalle al checkout.';


-- --------------------------------------------------------------------
--  2.4  VARIANTE_PRODUCTO — UNIDAD ATÓMICA DEL INVENTARIO  ★ CORE ★
-- --------------------------------------------------------------------
CREATE TABLE variante_producto (
    id_variante         INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_producto         VARCHAR(7)      NOT NULL,
    id_talla            INTEGER         NOT NULL,
    color               VARCHAR(30)     NOT NULL,
    sku                 VARCHAR(50)     NOT NULL,

    -- ── Contadores escribibles por la aplicación ─────────────────────
    var_saldo_inicial   INTEGER         NOT NULL DEFAULT 0,
    var_qty_ingresos    INTEGER         NOT NULL DEFAULT 0,
    var_qty_egresos     INTEGER         NOT NULL DEFAULT 0,
    var_qty_ajustes     INTEGER         NOT NULL DEFAULT 0,

    -- ── Saldo calculado: PG es el único dueño ────────────────────────
    var_saldo_final     INTEGER         GENERATED ALWAYS AS (
        var_saldo_inicial
        + var_qty_ingresos
        - var_qty_egresos
        + var_qty_ajustes
    ) STORED,

    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_variante_producto   PRIMARY KEY (id_variante),
    CONSTRAINT uq_var_sku             UNIQUE      (sku),
    CONSTRAINT uq_var_combinacion     UNIQUE      (id_producto, id_talla, color),

    CONSTRAINT fk_var_producto        FOREIGN KEY (id_producto)
        REFERENCES producto(id_producto)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_var_talla           FOREIGN KEY (id_talla)
        REFERENCES talla(id_talla)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT chk_var_saldo_ini      CHECK (var_saldo_inicial  >= 0),
    CONSTRAINT chk_var_qty_ing        CHECK (var_qty_ingresos   >= 0),
    CONSTRAINT chk_var_qty_egr        CHECK (var_qty_egresos    >= 0),

    -- Bloquea cualquier UPDATE que dejaría el stock en negativo
    CONSTRAINT chk_var_stock_no_neg   CHECK (
        (var_saldo_inicial + var_qty_ingresos - var_qty_egresos + var_qty_ajustes) >= 0
    )
);
COMMENT ON TABLE variante_producto IS
    'Unidad atómica de stock: 1 fila = 1 combinación producto+talla+color. Núcleo del inventario.';
COMMENT ON COLUMN variante_producto.var_saldo_final IS
    'GENERATED ALWAYS STORED: ini + ingresos - egresos + ajustes. Solo lectura — escrito por PG.';


-- --------------------------------------------------------------------
--  2.5  PRODUCTO_FOTOS — galería del e-commerce
-- --------------------------------------------------------------------
CREATE TABLE producto_fotos (
    id_foto         INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_producto     VARCHAR(7)      NOT NULL,
    url_foto        TEXT            NOT NULL,
    alt_text        VARCHAR(150),
    es_principal    BOOLEAN         NOT NULL DEFAULT FALSE,
    orden           INTEGER         NOT NULL DEFAULT 1,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_producto_fotos    PRIMARY KEY (id_foto),
    CONSTRAINT fk_foto_producto     FOREIGN KEY (id_producto)
        REFERENCES producto(id_producto)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT chk_foto_orden       CHECK (orden > 0),
    CONSTRAINT chk_foto_url         CHECK (LENGTH(TRIM(url_foto)) > 0)
);
COMMENT ON TABLE producto_fotos IS
    'Galería de imágenes en Azure Blob Storage. URL pública directa.';
COMMENT ON COLUMN producto_fotos.alt_text IS
    'Texto alternativo para accesibilidad y SEO';

-- Índice parcial: máximo 1 foto principal por producto
CREATE UNIQUE INDEX uq_producto_foto_principal
    ON producto_fotos (id_producto)
    WHERE es_principal = TRUE;

COMMENT ON INDEX uq_producto_foto_principal IS
    'Garantiza una única foto principal por producto.';


-- ════════════════════════════════════════════════════════════════════════
--  BLOQUE 3 — INVENTARIO (AJUSTES Y LEDGER)
-- ════════════════════════════════════════════════════════════════════════

-- --------------------------------------------------------------------
--  3.1  AJUSTE_INVENTARIO — cabecera
-- --------------------------------------------------------------------
CREATE TABLE ajuste_inventario (
    id_ajuste       INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_empleado     INTEGER         NOT NULL,
    fecha_ajuste    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    motivo          VARCHAR(200)    NOT NULL,
    estado          CHAR(3)         NOT NULL DEFAULT 'PRO',
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ajuste_inventario  PRIMARY KEY (id_ajuste),
    CONSTRAINT fk_aji_empleado       FOREIGN KEY (id_empleado)
        REFERENCES empleado(id_empleado)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_aji_estado        CHECK (estado IN ('PRO','ANU')),
    CONSTRAINT chk_aji_motivo        CHECK (LENGTH(TRIM(motivo)) >= 5)
);
COMMENT ON TABLE ajuste_inventario IS
    'Cabecera de ajuste de inventario (PRO=Procesado, ANU=Anulado)';


-- --------------------------------------------------------------------
--  3.2  DETALLE_AJUSTE — líneas
-- --------------------------------------------------------------------
CREATE TABLE detalle_ajuste (
    id_det_ajuste   INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_ajuste       INTEGER         NOT NULL,
    id_variante     INTEGER         NOT NULL,
    cantidad        INTEGER         NOT NULL,
    tipo_movimiento CHAR(3)         NOT NULL,
    CONSTRAINT pk_detalle_ajuste    PRIMARY KEY (id_det_ajuste),
    CONSTRAINT fk_dad_ajuste        FOREIGN KEY (id_ajuste)
        REFERENCES ajuste_inventario(id_ajuste)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_dad_variante      FOREIGN KEY (id_variante)
        REFERENCES variante_producto(id_variante)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_dad_cantidad     CHECK (cantidad > 0),
    CONSTRAINT chk_dad_tipo         CHECK (tipo_movimiento IN ('ING','EGR'))
);
COMMENT ON TABLE detalle_ajuste IS
    'Líneas de un ajuste apuntando a la variante específica';


-- --------------------------------------------------------------------
--  3.3  MOVIMIENTO_STOCK — ledger append-only
-- --------------------------------------------------------------------
CREATE TABLE movimiento_stock (
    id_movimiento   BIGINT          NOT NULL GENERATED ALWAYS AS IDENTITY,
    id_variante     INTEGER         NOT NULL,
    tipo            CHAR(3)         NOT NULL,
    cantidad        INTEGER         NOT NULL,
    referencia      VARCHAR(20),
    saldo_post      INTEGER         NOT NULL,
    fecha           TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    observacion     VARCHAR(200),
    id_empleado     INTEGER,
    CONSTRAINT pk_movimiento_stock  PRIMARY KEY (id_movimiento),
    CONSTRAINT fk_mst_variante      FOREIGN KEY (id_variante)
        REFERENCES variante_producto(id_variante)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_mst_empleado      FOREIGN KEY (id_empleado)
        REFERENCES empleado(id_empleado)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT chk_mst_tipo         CHECK (tipo IN ('ING','EGR','AJU','DEV')),
    CONSTRAINT chk_mst_cantidad     CHECK (cantidad > 0),
    CONSTRAINT chk_mst_saldo_post   CHECK (saldo_post >= 0)
);
COMMENT ON TABLE movimiento_stock IS
    'Ledger append-only — nunca UPDATE, solo INSERT. Auditoría completa de stock.';


-- ════════════════════════════════════════════════════════════════════════
--  BLOQUE 4 — PROMOCIONES
-- ════════════════════════════════════════════════════════════════════════

CREATE TABLE promocion (
    id_promocion         INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nombre               VARCHAR(100)    NOT NULL,
    descripcion          TEXT,
    porcentaje_descuento NUMERIC(5,2),
    fecha_inicio         TIMESTAMP       NOT NULL,
    fecha_fin            TIMESTAMP       NOT NULL,
    estado               CHAR(3)         NOT NULL DEFAULT 'ACT',
    created_at           TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_promocion         PRIMARY KEY (id_promocion),
    CONSTRAINT chk_promo_descuento  CHECK (porcentaje_descuento IS NULL
                                        OR porcentaje_descuento BETWEEN 0 AND 100),
    CONSTRAINT chk_promo_fechas     CHECK (fecha_fin > fecha_inicio),
    CONSTRAINT chk_promo_estado     CHECK (estado IN ('ACT','INA'))
);
COMMENT ON TABLE promocion IS
    'Campañas de descuento con vigencia (Black Friday, mid-season sale, etc.)';


CREATE TABLE promocion_detalle (
    id_prom_detalle INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_promocion    INTEGER         NOT NULL,
    id_producto     VARCHAR(7)      NOT NULL,
    CONSTRAINT pk_promocion_detalle PRIMARY KEY (id_prom_detalle),
    CONSTRAINT uq_prom_producto     UNIQUE      (id_promocion, id_producto),
    CONSTRAINT fk_prd_promocion     FOREIGN KEY (id_promocion)
        REFERENCES promocion(id_promocion)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_prd_producto      FOREIGN KEY (id_producto)
        REFERENCES producto(id_producto)
        ON UPDATE CASCADE ON DELETE CASCADE
);
COMMENT ON TABLE promocion_detalle IS
    'Asocia productos a promociones. Aplica a todas las variantes del producto.';


-- ════════════════════════════════════════════════════════════════════════
--  BLOQUE 5 — VENTAS Y CHECKOUT
-- ════════════════════════════════════════════════════════════════════════

-- --------------------------------------------------------------------
--  5.1  CARRITO — uno por cliente, persistente
-- --------------------------------------------------------------------
CREATE TABLE carrito (
    id_carrito      INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_cliente      INTEGER         NOT NULL,
    fecha_creacion  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_carrito           PRIMARY KEY (id_carrito),
    CONSTRAINT uq_car_cliente       UNIQUE      (id_cliente),
    CONSTRAINT fk_car_cliente       FOREIGN KEY (id_cliente)
        REFERENCES cliente(id_cliente)
        ON UPDATE CASCADE ON DELETE CASCADE
);
COMMENT ON TABLE carrito IS
    'Carrito persistente del cliente (1:1). Se vacía al confirmar una factura.';


-- --------------------------------------------------------------------
--  5.2  CARRITO_DETALLE — líneas apuntando a la VARIANTE
-- --------------------------------------------------------------------
CREATE TABLE carrito_detalle (
    id_carrito_det  INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_carrito      INTEGER         NOT NULL,
    id_variante     INTEGER         NOT NULL,
    cantidad        INTEGER         NOT NULL,
    fecha_agregado  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_carrito_detalle   PRIMARY KEY (id_carrito_det),
    CONSTRAINT uq_car_det_var       UNIQUE      (id_carrito, id_variante),
    CONSTRAINT fk_cad_carrito       FOREIGN KEY (id_carrito)
        REFERENCES carrito(id_carrito)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_cad_variante      FOREIGN KEY (id_variante)
        REFERENCES variante_producto(id_variante)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_cad_cantidad     CHECK (cantidad > 0)
);
COMMENT ON TABLE carrito_detalle IS
    'Items del carrito. UNIQUE (carrito, variante) — agregar la misma talla suma cantidad.';


-- --------------------------------------------------------------------
--  5.3  FACTURA — comprobante de venta (cabecera)
-- --------------------------------------------------------------------
CREATE TABLE factura (
    id_factura          VARCHAR(15)     NOT NULL,
    id_cliente          INTEGER         NOT NULL,
    id_empleado         INTEGER,
    id_direccion_envio  INTEGER,
    subtotal            NUMERIC(14,3)   NOT NULL DEFAULT 0,
    descuento_total     NUMERIC(14,3)   NOT NULL DEFAULT 0,
    total               NUMERIC(14,3)   NOT NULL DEFAULT 0,
    fecha_emision       TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado              CHAR(3)         NOT NULL DEFAULT 'EMI',
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_factura           PRIMARY KEY (id_factura),
    CONSTRAINT fk_fac_cliente       FOREIGN KEY (id_cliente)
        REFERENCES cliente(id_cliente)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_fac_empleado      FOREIGN KEY (id_empleado)
        REFERENCES empleado(id_empleado)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_fac_direccion     FOREIGN KEY (id_direccion_envio)
        REFERENCES direccion_cliente(id_direccion)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_fac_subtotal     CHECK (subtotal        >= 0),
    CONSTRAINT chk_fac_descuento    CHECK (descuento_total >= 0),
    CONSTRAINT chk_fac_total        CHECK (total           >= 0),
    CONSTRAINT chk_fac_estado       CHECK (estado IN ('EMI','PAG','ENV','ENT','ANU')),
    CONSTRAINT chk_fac_consistencia CHECK (total = subtotal - descuento_total),
    CONSTRAINT chk_fac_formato_sri  CHECK (id_factura ~ '^\d{3}-\d{3}-\d{9}$')
);
COMMENT ON TABLE factura IS
    'Cabecera de factura. Estados: EMI=Emitida, PAG=Pagada, ENV=Enviada, ENT=Entregada, ANU=Anulada';
COMMENT ON COLUMN factura.id_factura IS
    'Formato SRI Ecuador: 001-001-XXXXXXXXX (validado por regex)';
COMMENT ON COLUMN factura.id_empleado IS
    'NULL para ventas online auto-procesadas (sin vendedor humano)';
COMMENT ON COLUMN factura.id_direccion_envio IS
    'Dirección a la que se envía. NULL solo si es retiro en local.';


-- --------------------------------------------------------------------
--  5.4  DETALLE_FACTURA — líneas de venta
-- --------------------------------------------------------------------
CREATE TABLE detalle_factura (
    id_factura      VARCHAR(15)     NOT NULL,
    id_variante     INTEGER         NOT NULL,
    cantidad        INTEGER         NOT NULL,
    precio_unitario NUMERIC(14,3)   NOT NULL,
    descuento_item  NUMERIC(14,3)   NOT NULL DEFAULT 0,
    subtotal_linea  NUMERIC(14,3)   GENERATED ALWAYS AS (
        (cantidad * precio_unitario) - descuento_item
    ) STORED,
    CONSTRAINT pk_detalle_factura   PRIMARY KEY (id_factura, id_variante),
    CONSTRAINT fk_dfa_factura       FOREIGN KEY (id_factura)
        REFERENCES factura(id_factura)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_dfa_variante      FOREIGN KEY (id_variante)
        REFERENCES variante_producto(id_variante)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_dfa_cantidad     CHECK (cantidad        > 0),
    CONSTRAINT chk_dfa_precio       CHECK (precio_unitario >= 0),
    CONSTRAINT chk_dfa_descuento    CHECK (descuento_item  >= 0),
    CONSTRAINT chk_dfa_descuento_max CHECK (descuento_item <= cantidad * precio_unitario)
);
COMMENT ON TABLE detalle_factura IS
    'Líneas de venta. Snapshot de precio_unitario al momento de la compra.';


-- --------------------------------------------------------------------
--  5.5  PAGO — registro de pagos (Stripe, transferencia, etc.)
-- --------------------------------------------------------------------
CREATE TABLE pago (
    id_pago             INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_factura          VARCHAR(15)     NOT NULL,
    metodo              VARCHAR(20)     NOT NULL,
    monto               NUMERIC(14,3)   NOT NULL,
    referencia_externa  VARCHAR(100),
    estado              CHAR(3)         NOT NULL DEFAULT 'PEN',
    fecha               TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_pago         PRIMARY KEY (id_pago),
    CONSTRAINT fk_pago_factura FOREIGN KEY (id_factura)
        REFERENCES factura(id_factura)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_pago_monto  CHECK (monto > 0),
    CONSTRAINT chk_pago_metodo CHECK (metodo IN ('STRIPE','TRANSFERENCIA','EFECTIVO','OTRO')),
    CONSTRAINT chk_pago_estado CHECK (estado IN ('PEN','COM','FAL','REE'))
);
COMMENT ON TABLE pago IS
    'Pagos asociados a una factura. Estados: PEN=Pendiente, COM=Completado, FAL=Fallido, REE=Reembolsado';
COMMENT ON COLUMN pago.referencia_externa IS
    'payment_intent_id de Stripe, número de transferencia, etc. Para conciliar con el proveedor.';


-- ════════════════════════════════════════════════════════════════════════
--  BLOQUE 6 — ASISTENTE IA (RAG: pgvector + Voyage AI + Anthropic)
-- ════════════════════════════════════════════════════════════════════════

-- --------------------------------------------------------------------
--  6.1  PRODUCTO_AI — descripción rica + embedding por producto
--       Llenado por el flujo de indexación del backoffice.
--       Embedding: voyage-3 (1024 dims, cosine similarity)
-- --------------------------------------------------------------------
CREATE TABLE producto_ai (
    id_producto         VARCHAR(7)      NOT NULL,
    descripcion_larga   TEXT            NOT NULL,
    bullet_points       JSONB,
    tags_estilo         JSONB,
    embedding           vector(1024),
    modelo_generacion   VARCHAR(50)     NOT NULL,
    modelo_embedding    VARCHAR(50)     NOT NULL,
    fecha_generacion    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version             INTEGER         NOT NULL DEFAULT 1,
    CONSTRAINT pk_producto_ai      PRIMARY KEY (id_producto),
    CONSTRAINT fk_pai_producto     FOREIGN KEY (id_producto)
        REFERENCES producto(id_producto)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT chk_pai_descripcion CHECK (LENGTH(TRIM(descripcion_larga)) >= 50)
);
COMMENT ON TABLE producto_ai IS
    'Contenido IA por producto: descripción larga + embedding vectorial. Regenerable a placer.';
COMMENT ON COLUMN producto_ai.embedding IS
    'Vector 1024-dim de voyage-3. Búsqueda con operador <=> (cosine distance).';
COMMENT ON COLUMN producto_ai.bullet_points IS
    'Array JSON: ["100% algodón", "Oversize fit", "Estampado serigrafiado", ...]';
COMMENT ON COLUMN producto_ai.tags_estilo IS
    'Array JSON: ["dark", "y2k", "minimal", "techwear", ...]';
COMMENT ON COLUMN producto_ai.version IS
    'Incrementa cada regeneración. Útil para A/B testing de prompts.';


-- --------------------------------------------------------------------
--  6.2  CHAT_SESION — sesiones del asistente de compra
--       Permite cliente anónimo (id_cliente NULL).
-- --------------------------------------------------------------------
CREATE TABLE chat_sesion (
    id_sesion               UUID            NOT NULL DEFAULT gen_random_uuid(),
    id_cliente              INTEGER,
    fecha_inicio            TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_ultimo_mensaje    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_agent              VARCHAR(255),
    ip_origen               VARCHAR(45),
    CONSTRAINT pk_chat_sesion   PRIMARY KEY (id_sesion),
    CONSTRAINT fk_chs_cliente   FOREIGN KEY (id_cliente)
        REFERENCES cliente(id_cliente)
        ON UPDATE CASCADE ON DELETE SET NULL
);
COMMENT ON TABLE chat_sesion IS
    'Sesión del asistente de compra IA. id_cliente NULL = sesión anónima.';
COMMENT ON COLUMN chat_sesion.ip_origen IS
    'IPv4 o IPv6 (45 chars cubre IPv6 con prefix). Útil para detectar abuso.';


-- --------------------------------------------------------------------
--  6.3  CHAT_MENSAJE — mensajes append-only del chat
-- --------------------------------------------------------------------
CREATE TABLE chat_mensaje (
    id_mensaje              BIGINT          NOT NULL GENERATED ALWAYS AS IDENTITY,
    id_sesion               UUID            NOT NULL,
    rol                     VARCHAR(10)     NOT NULL,
    contenido               TEXT            NOT NULL,
    productos_referenciados JSONB,
    tokens_input            INTEGER,
    tokens_output           INTEGER,
    fecha                   TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_chat_mensaje  PRIMARY KEY (id_mensaje),
    CONSTRAINT fk_chm_sesion    FOREIGN KEY (id_sesion)
        REFERENCES chat_sesion(id_sesion)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT chk_chm_rol      CHECK (rol IN ('user', 'assistant')),
    CONSTRAINT chk_chm_contenido CHECK (LENGTH(TRIM(contenido)) > 0)
);
COMMENT ON TABLE chat_mensaje IS
    'Mensajes del chat. Append-only — nunca UPDATE, solo INSERT.';
COMMENT ON COLUMN chat_mensaje.productos_referenciados IS
    'Array JSON de id_producto que el asistente mostró en este mensaje. Métrica de qué productos recomienda más.';
COMMENT ON COLUMN chat_mensaje.tokens_input IS
    'Tokens consumidos en el call a Claude. NULL para mensajes del usuario.';


-- ════════════════════════════════════════════════════════════════════════
--  BLOQUE 7 — TRIGGERS DE updated_at
--  Aplicados solo en tablas que se modifican (no en append-only).
-- ════════════════════════════════════════════════════════════════════════

CREATE TRIGGER tg_rol_updated_at
    BEFORE UPDATE ON rol
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TRIGGER tg_empleado_updated_at
    BEFORE UPDATE ON empleado
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TRIGGER tg_usuarios_backoffice_updated_at
    BEFORE UPDATE ON usuarios_backoffice
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TRIGGER tg_cliente_updated_at
    BEFORE UPDATE ON cliente
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TRIGGER tg_direccion_cliente_updated_at
    BEFORE UPDATE ON direccion_cliente
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TRIGGER tg_categoria_producto_updated_at
    BEFORE UPDATE ON categoria_producto
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TRIGGER tg_talla_updated_at
    BEFORE UPDATE ON talla
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TRIGGER tg_producto_updated_at
    BEFORE UPDATE ON producto
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TRIGGER tg_variante_producto_updated_at
    BEFORE UPDATE ON variante_producto
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TRIGGER tg_ajuste_inventario_updated_at
    BEFORE UPDATE ON ajuste_inventario
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TRIGGER tg_promocion_updated_at
    BEFORE UPDATE ON promocion
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TRIGGER tg_carrito_updated_at
    BEFORE UPDATE ON carrito
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TRIGGER tg_factura_updated_at
    BEFORE UPDATE ON factura
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();


-- ════════════════════════════════════════════════════════════════════════
--  BLOQUE 8 — ÍNDICES DE RENDIMIENTO
-- ════════════════════════════════════════════════════════════════════════

-- ── Catálogo público ────────────────────────────────────────────────────
CREATE INDEX idx_producto_categoria
    ON producto (id_categoria)
    WHERE estado_prod = 'ACT';
COMMENT ON INDEX idx_producto_categoria IS
    'Acelera el listado del catálogo público filtrado por categoría';

CREATE INDEX idx_variante_producto
    ON variante_producto (id_producto);

CREATE INDEX idx_variante_sin_stock
    ON variante_producto (id_producto)
    WHERE var_saldo_final = 0;
COMMENT ON INDEX idx_variante_sin_stock IS
    'Dashboards de bodega: qué variantes están agotadas';

-- ── Inventario ──────────────────────────────────────────────────────────
CREATE INDEX idx_movimiento_variante_fecha
    ON movimiento_stock (id_variante, fecha DESC);

-- ── Ventas ──────────────────────────────────────────────────────────────
CREATE INDEX idx_factura_cliente_fecha
    ON factura (id_cliente, fecha_emision DESC);

CREATE INDEX idx_factura_estado
    ON factura (estado, fecha_emision DESC);

CREATE INDEX idx_pago_factura
    ON pago (id_factura);

-- ── Promociones ─────────────────────────────────────────────────────────
CREATE INDEX idx_promocion_vigente
    ON promocion (fecha_inicio, fecha_fin)
    WHERE estado = 'ACT';

-- ── Carrito ─────────────────────────────────────────────────────────────
CREATE INDEX idx_carrito_detalle_variante
    ON carrito_detalle (id_variante);

-- ── Direcciones ─────────────────────────────────────────────────────────
CREATE INDEX idx_direccion_cliente
    ON direccion_cliente (id_cliente)
    WHERE activa = TRUE;

-- ── Tokens ──────────────────────────────────────────────────────────────
CREATE INDEX idx_token_cliente_tipo
    ON token_recuperacion (id_cliente, tipo)
    WHERE usado = FALSE;

-- ── Asistente IA ────────────────────────────────────────────────────────
-- Búsqueda semántica con HNSW (cosine distance)
CREATE INDEX idx_producto_ai_embedding
    ON producto_ai USING hnsw (embedding vector_cosine_ops);
COMMENT ON INDEX idx_producto_ai_embedding IS
    'HNSW para búsqueda semántica con operador <=>. Acelera ORDER BY embedding <=> query_vec';

-- Memoria del chat: últimos N mensajes de una sesión
CREATE INDEX idx_chat_mensaje_sesion
    ON chat_mensaje (id_sesion, fecha);

-- Histórico de chats por cliente (para que vea sus conversaciones)
CREATE INDEX idx_chat_sesion_cliente
    ON chat_sesion (id_cliente, fecha_inicio DESC)
    WHERE id_cliente IS NOT NULL;


-- ════════════════════════════════════════════════════════════════════════
--  BLOQUE 9 — AUDITORÍA GENERAL
-- ════════════════════════════════════════════════════════════════════════

CREATE TABLE audit_log (
    id_audit        BIGINT          NOT NULL GENERATED ALWAYS AS IDENTITY,
    tabla           VARCHAR(50)     NOT NULL,
    id_registro     VARCHAR(50)     NOT NULL,
    accion          CHAR(6)         NOT NULL,
    payload_antes   JSONB,
    payload_despues JSONB,
    id_usuario_bo   INTEGER,
    id_cliente      INTEGER,
    ip              VARCHAR(45),
    user_agent      VARCHAR(255),
    fecha           TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_audit_log     PRIMARY KEY (id_audit),
    CONSTRAINT fk_aud_usuario   FOREIGN KEY (id_usuario_bo)
        REFERENCES usuarios_backoffice(id_usuario)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_aud_cliente   FOREIGN KEY (id_cliente)
        REFERENCES cliente(id_cliente)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT chk_aud_accion   CHECK (accion IN ('INSERT','UPDATE','DELETE','LOGIN','LOGOUT','EXPORT'))
);

COMMENT ON TABLE audit_log IS
    'Ledger append-only de auditoría general. NUNCA se modifica ni se elimina.';
COMMENT ON COLUMN audit_log.tabla IS
    'Nombre de la tabla afectada: producto, cliente, factura, etc.';
COMMENT ON COLUMN audit_log.id_registro IS
    'PK del registro afectado como string (cubre INTEGER, VARCHAR y UUID)';
COMMENT ON COLUMN audit_log.accion IS
    'INSERT/UPDATE/DELETE = cambios de datos | LOGIN/LOGOUT = sesiones | EXPORT = descarga de datos';
COMMENT ON COLUMN audit_log.payload_antes IS
    'Snapshot del registro ANTES del cambio. NULL en INSERT.';
COMMENT ON COLUMN audit_log.payload_despues IS
    'Snapshot del registro DESPUÉS del cambio. NULL en DELETE lógico solo guarda estado nuevo.';
COMMENT ON COLUMN audit_log.id_usuario_bo IS
    'NULL si la acción la hizo un cliente o un proceso automático del sistema.';
COMMENT ON COLUMN audit_log.id_cliente IS
    'NULL si la acción la hizo un empleado del backoffice.';

CREATE INDEX idx_audit_tabla_registro
    ON audit_log (tabla, id_registro, fecha DESC);
COMMENT ON INDEX idx_audit_tabla_registro IS
    'Acelera "dame el historial completo de este registro específico"';

CREATE INDEX idx_audit_usuario
    ON audit_log (id_usuario_bo, fecha DESC)
    WHERE id_usuario_bo IS NOT NULL;

CREATE INDEX idx_audit_cliente
    ON audit_log (id_cliente, fecha DESC)
    WHERE id_cliente IS NOT NULL;

CREATE INDEX idx_audit_fecha
    ON audit_log (fecha DESC);

-- ████████████████████████████████████████████████████████████████████████
--  FIN DEL SCRIPT
-- ────────────────────────────────────────────────────────────────────────
--  RESUMEN FINAL:
--    Schema         :  1   (vortex)
--    Extensions     :  2   (vector, pgcrypto)
--    Tablas         : 25
--    Funciones      :  1   (fn_set_updated_at)
--    Triggers       : 13   (updated_at automático)
--    GENERATED cols :  2   (var_saldo_final, subtotal_linea)
--    Sequences      :  1   (seq_producto)
--    Índices extra  : 14
--    Índices HNSW   :  1   (embeddings vectoriales)
--
--  CHECKLIST POST-DEPLOY:
--    [ ] npx prisma db pull         → sincronizar schema.prisma
--    [ ] Crear seed.sql con:
--        • roles base (admin, vendedor, bodega)
--        • categorías iniciales (HOO, TEE, PAN, ACC)
--        • tallas (XS, S, M, L, XL, ÚN)
--    [ ] Verificar pgvector: SELECT * FROM pg_extension WHERE extname='vector';
--    [ ] Crear primer empleado admin manualmente
-- ████████████████████████████████████████████████████████████████████████
